source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '14.0'
$casVersion = '~> 4.5.4'

target 'CASSwiftUIDemoApp' do
  pod 'CleverAdsSolutions-Base', $casVersion
end
