source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'CASSample' do
  pod 'CleverAdsSolutions-SDK', '>= 1.6.8'
  pod 'CleverAdsSolutions-Promo', '>= 1.6.8'
end
