source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'CASSample' do
  ### Default integration:
  pod 'CleverAdsSolutions-SDK', '>= 1.8.0'
  ### Advanced integration:
  #pod 'CleverAdsSolutions-SDK/General'
  #pod 'CleverAdsSolutions-SDK/SuperAwesome'
  #pod 'CleverAdsSolutions-SDK/MyTarget'
  #pod 'CleverAdsSolutions-SDK/AmazonAd'
  #pod 'CleverAdsSolutions-SDK/MobFox'
  ### Cross Promotion integration:
  #pod 'CleverAdsSolutions-Promo', '>= 1.8.0'
end
