source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '10.0'
use_frameworks!

$casVersion = '~> 2.6.6'

target 'CASSample' do
  ### Default integration:
  pod 'CleverAdsSolutions-SDK', $casVersion
  ### Advanced integration:
  # pod 'CleverAdsSolutions-SDK/GoogleAds', $casVersion
  # pod 'CleverAdsSolutions-SDK/UnityAds', $casVersion
  # pod 'CleverAdsSolutions-SDK/AppLovin', $casVersion
  # pod 'CleverAdsSolutions-SDK/InMobi', $casVersion
  # ... any other combination of networks
  ### Cross Promotion integration:
  pod 'CleverAdsSolutions-Promo', $casVersion
end
