source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '13.0'
$casVersion = '~> 4.6.2'

target 'CASSample' do
  pod 'CleverAdsSolutions-Base', $casVersion
end
