source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '13.0'
use_frameworks! :linkage => :static
$casVersion = '~> 3.9.9'

target 'CASSample' do
  pod 'CleverAdsSolutions-Base', $casVersion
  pod 'CleverAdsSolutions-SDK/GoogleAds', $casVersion
end
